routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\models\user;

URL::forceRootURL(env('APP_URL'));

//Enable logout via get
Route::get('logout', function (){
    Auth::logout();
    return redirect('/login');
});

Route::get('datenschutz', function () {
    return view('datenschutz');
});



Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {  //redirect to create entry
        return redirect('/entry/create');
    });

    Route::get('/email_overview', 'user_controller@show_email_overview');

//Route::get('/summary', 'summary_controller@display');

    Route::resource('user', 'user_controller', ['except' => ['create', 'store']]);
    Route::resource('entry', 'entry_controller');
    Route::resource('project', 'project_controller');
    Route::resource('palaverItem', 'palaver_controller');
    Route::resource('pilot', 'pilot_controller', ['only' => ['destroy', 'create', 'store']]);
//Route::post('/home', 'HomeController@index');

    Route::post('/palaverItem/{palaverItem}/ajax', 'ajax_controller@palaver');

    Route::get('/fliegen', function (\Illuminate\Http\Request $request) {
        $user = "";
        if (isset($request->date)) {
            $date = \Carbon\Carbon::parse($request->date)->toDateString();
        } else {
            $date = \Carbon\Carbon::now('Europe/Berlin')->addDay(1)->subHour(9)->toDateString(); //Neuer Tag wird immmer ab 9 Uhr angezeigt
        }
        //Flugberechtigte Nutzer Filtern
        $user = User::withoutGlobalScope('jungeGruppe')->with('versions', 'status', 'entries')->get()->filter(function (user $item) {
            return $item->getFlugberechtigtAttribute(Help::currentYear()) || $item->status->name == 'Alter Sack';
        });


        return view('fliegen.index')->with('pilots', \App\models\pilot::where('date', $date)->get())->with('cars', \App\models\car::where('date', $date)->get())->with('airplanes', \App\models\project::withoutGlobalScope('EDEP')->where('isAirplane',1)->where('active','1')->get())->with('date', $date)->with('users', $user);
    });
    /*
        Route::post('/car/create', function (\Illuminate\Http\Request $request) {

            $car = \App\models\car::create($request->except(['_token']));
            $car->save();

            return back();

        });*/
    Route::post('/car/create','car_controller@store');
    Route::delete('/car/{car}','car_controller@destroy');
    Route::put('/car/{car}','car_controller@addPassenger');

    Route::delete('/car/{car}/{user}','car_controller@removePassenger');

    Route::post('/fliegen/ajax', 'ajax_controller@fliegen');

// Authentication Routes...
    Route::get('logout', 'Auth\LoginController@logout');

// Registration Routes...
    Route::get('/register', 'user_controller@create');
    Route::post('/register', 'user_controller@store');


    if(env('PALAVER_FEATURES')) {
        Route::get('/palaverIndex', 'palaver_controller@palaverIndex');
        Route::get('/pdf', 'palaver_controller@pdf');
        Route::get('/palaver/create', 'palaver_controller@create_palaver');
        Route::post('palaver/create', 'palaver_controller@save_anwesenheit');
        Route::get('/palaver/{palaver}/edit', 'palaver_controller@editAnwesenheit');
        Route::post('/palaver/{palaver}/edit', 'palaver_controller@updateAnwesenheit');
        Route::get('/palaver/{palaver}', 'palaver_controller@pdf');
        Route::get('palaver', 'palaver_controller@create_anwesenheit');
        Route::post('palaver_save_data', 'palaver_controller@save_data');
        Route::get('/palaver_view', 'palaver_controller@palaver');

    }

});

Route::get('/loginAs/{user}', function (User $user) {
    if (Auth::user()->id == 1) {
        Auth::logout();
        Auth::loginUsingId($user->id);
        return redirect('/entry/create');
    } else {
        dd("GTFO");
    }
});





Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');


Route::get('statistics', function (\Illuminate\Http\Request $request) {
    if (env('SHOW_STATISTICS') || Auth::user()->is_admin) {
        if (env('ALLOW_PAST_YEARS')) {
            $year = $request->year;
            if (empty($year)) {
                $year = Help::currentYear();
            }
        } else {
            $year = Help::currentYear();
        }

        $statistic = DB::select("SELECT users.first_name, users.nickname, SUM(entries.work_time) AS time, projects.name AS project from users JOIN entries on users.id = entries.user_id JOIN palaverItems on entries.palaverItem_id = palaverItems.id JOIN projects on palaverItems.project_id = projects.id GROUP BY users.id,projects.id
ORDER BY projects.id");

        return view('statistics')->with('year', $year)->with('stats', $statistic);
    } else {
        abort(403, "Statistik deaktiviert, hier gibts nix zu sehen");
    }
});

app/models/palaverItem.php
<?php

namespace App\models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;


/**
 * App\models\palaverItem
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $status
 * @property boolean $done
 * @property boolean $canceled
 * @property integer $project_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $date
 * @property-read \App\models\project $project
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\models\User[] $user
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\models\entry[] $entries
 * @property-read mixed $real_status
 * @property-read mixed $responsible_users
 * @property-read mixed $formatted_work_time
 * @property-read mixed $total_work_time
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereTitle($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereDescription($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereStatus($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereDone($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereCanceled($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereProjectId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem active()
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem whereDate($value)
 * @mixin \Eloquent
 * @property-read mixed $work_this_week
 * @method static \Illuminate\Database\Query\Builder|\App\models\palaverItem activeScope()
 * @property-read mixed $active
 */
class palaverItem extends Model {
    protected $fillable = [
            'title', 'description', 'nickname', 'status', 'project_id', 'done', 'canceled', 'date'
    ];

    protected $table = 'palaverItems';

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('orderBy', function ($builder) {
            $builder->orderBy('title', 'asc');
        });
    }

    public function project() {
        return $this->belongsTo('App\models\project');
    }

    public function user() {
        return $this->belongsToMany('App\models\user', 'palaverItem_user', 'palaverItem_id', 'user_id');
    }

    public function entries() {
        return $this->hasMany('App\models\entry', 'palaverItem_id');
    }

    public function getRealStatusAttribute() {
        //return $this->status;
        if ($this->done) {
            return "Fertig";
        }

        if ($this->canceled) {
            return "Abgebrochen";
        }

        if (!$this->status == '') {
            return $this->status;
        }

        if ($this->entries->isEmpty()) {
            return "Noch nichts passiert";
        }


        return $this->entries->sortBy('date')->first()->description;
    }



    //gibt Nutzer als String zurück (Nutzer1, Nuter2, ...
    public function getResponsibleUsersAttribute() {

        $users = $this->user;
        if ($users->isEmpty()) {
            return "Niemand";
        }
        $result = "";
        for ($x = 0; $x < sizeof($users) - 1; $x++) {
            $result = $result . $users[$x]->short_name . ', ';
        }
        return $result . $users[sizeof($users) - 1]->short_name;

    }

    public function getActiveAttribute() {
        return !($this->canceled || $this->done);
    }

    //gibt nur nicht abgeschlossene Projekte oder solche, die in der vergangenen 6 Tagen abgescshlossen wurden
    public function scopeActive($query) {
        return $query->where(function ($query) {
            $query->where('done', 0)->where('canceled', 0);
        })->orwhere('updated_at', '>', Carbon::now()->subWeek()->addDay()->toDateString());
    }

    public function getFormattedWorkTimeAttribute() {
        $time = $this->getTotalWorkTimeAttribute();
        $hours = floor($time / 60);
        $minutes = $time % 60;
        return $hours . " Stunden, " . $minutes . " Minuten";
    }

    public function getTotalWorkTimeAttribute() {
        return $this->entries->sum('work_time');
    }

    public function getTotalWorkTime($year) {

        $entries = $this->entries;

        return $entries->sum('work_time');
    }

    public function getWorkThisWeekAttribute() {
        $cache_key = $this->id.'palaverItemWorkThisWeek';

            if(Cache::has($cache_key)){
                return Cache::get($cache_key);

            }

            $workThisWeek = $this->entries->filter(function (entry $entry) {
                return Carbon::parse($entry->date)->gte(Carbon::today()->startOfWeek());
            })->sum('work_time');

            $expires_at = Carbon::now()->addWeek();
            Cache::put($cache_key, $workThisWeek, $expires_at);

            return $workThisWeek;



    }

    public function getWorkThisMonthAttribute() {
        $cache_key = $this->id.'palaverItemWorkThisMonth';

        if(Cache::has($cache_key)){
            return Cache::get($cache_key);
        }

        $workThisMonth = $this->entries->filter(function(entry $entry){
            return Carbon::parse($entry->date)->gte(Carbon::today()->startOfMonth());
        })->sum('work_time');

        $expires_at = Carbon::now()->addWeek();
        Cache::put($cache_key, $workThisMonth, $expires_at);
        return $workThisMonth;

    }

    public function getWorkThisYearAttribute() {
        $cache_key= $this->id.'palaverItemWorkThisYear';

        if(Cache::has($cache_key)){
            return Cache::get($cache_key);
        }

        $workThisYear = $this->entries->filter(function (entry $entry) {
                return Carbon::parse($entry->date)->gte(Carbon::create(\Help::currentYear() - 1, env('BEGIN_YEAR_MONTH'), 01, 0, 0));
            })->sum('work_time');

        $expires_at = Carbon::now()->addWeek();
        Cache::put($cache_key, $workThisYear, $expires_at);


        return $workThisYear;

    }



}

app/Http/Controllers/project_controller.php
<?php

namespace App\Http\Controllers;

use App\models\project;
use App\models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Session;

class project_controller extends Controller
{
    public function __construct() {
        //$this->middleware('palaver_auth', ['except' => ['index', 'show']]);
    }


    public function create() {

        return view('project.create')->with('users', User::get()->pluck('full_name', 'id'));
    }

    public function store(Request $request) {

        $this->validate($request,
                ['name' => 'required|string|min:3|unique:projects,name',
                    //    'description' => 'required|min:10',
                ]);

        $project = new project();
        $project->name = $request->name;
        $project->description = $request->description;
        $project->user_id = $request->user_id;
        if (isset($request->isAirplane)) {
            $project->isAirplane = 1;
        } else {
            $project->isAirplane = 0;
        }

        $project->active = 1; //Neu angelegtes Projekt muss aktiv sein

        $this->authorize('store', $project);

        $success = $project->save();

        if ($success) {
            Session::flash('alert-success', 'Projekt angelegt');
        } else {
            Session::flash('alert-danger', 'Das hat nicht funktioniert');
        }

        if (isset($request->type)) {
            if ($request->type == 'p') {
                return redirect('/palaver_view');
            } else if ($request->type == 'np') {
                return redirect('/palaverItem');
            }
        }
        return redirect('/project/' . $project->id);


    }

    public function index(Request $request) {

        if($request->show_all){
            $projects = project::with('palaverItems', 'palaverItems.entries', 'supervisor')->get();
        }

        else {
            $projects = project::active()->with(['palaverItems' => function ($q) {
                return $q->active();
            }], 'palaverItems.entries', 'supervisor')->get();
        }

        $date= Carbon::today()->subMonthNoOverflow()->day(1);
        $date2 = Carbon::today()->subMonthNoOverflow()->endOfMonth();


        $query="SELECT users.first_name, users.nickname, SUM(entries.work_time) AS 'Zeit' FROM users JOIN entries ON entries.user_id=users.id WHERE entries.date >= '". $date->toDateString() ."' AND entries.date <='". $date2->toDateString() ."' GROUP BY users.id, users.first_name, users.nickname ORDER BY SUM(entries.work_time) DESC LIMIT 3";


        $top3=\DB::select($query);

        //dd($date,$date2,$top3);

        return view('project.index')->with('projects', $projects)->with('show_all',$request->show_all)->with('top3',$top3);
    }

    public function update(Request $request, project $project) {

        $this->authorize('update', $project);
        $this->validate($request,
                ['name'        => 'required|unique:projects,name,' . $project->id,
                    //   'description' => 'required|min:10',
                ]);

        $project->name = $request->name;
        $project->description = $request->description;

        $project->user_id = $request->user_id;



        if (isset($request->flightReady)) {
            $project->flightReady = 1;
        } else {
            $project->flightReady = 0;
        }
        if (!isset($request->active) && \Auth::user()->is_admin) {
            $project->active = 0;
        }

        if (!isset($request->isAirplane) && \Auth::user()->is_admin) {
            $project->isAirplane = 0;
        }
        if(isset($request->isAirplane) && \Auth::user()->is_admin){
            $project->isAirplane=1;
        }
        if (Auth::user()->is_admin || !isset($project)) {
            if (isset($request->active)) {
                $project->active = true;
            } else {
                $project->active = false;
            }
        }

        $success = $project->save();

        if ($success) {
            Session::flash('alert-success', 'Projekt gespeichert');
        } else {
            Session::flash('alert-danger', 'Das hat nicht funktioniert');
        }

        try {
            Session::flash('hook', $project->palaverItems->first()->id);
        } catch (\Exception $e) {
            \Log::alert("Noch keine PalaverItems für " . $project->name);
        }

        if (isset($request->type)) {
            if ($request->type == 'p') {
                return redirect('/palaver_view');
            } else if ($request->type == 'np') {
                return redirect('/palaverItem');
            }
        }

        return redirect('/project/'.$project->id);
    }

    public function show(Request $request,project $project ) {

        if($request->show_all){
            $project=$project->load('palaverItems','palaverItems.entries','palaverItems.user');
        }

        else{

            $project = $project->load(['palaverItems' => function ($q) {
                return $q->where('done', '=', 0)->where('canceled', '=', 0)->orWhere('updated_at', '>', Carbon::today()->subWeek()->toDateString());
//TODO check for correct project selection
            }]);
        }

        return view('project.view')->with('project',$project)->with('show_all',$request->show_all);
    }

    public function edit(project $project) {
        return view('project.edit')->with('project', $project)->with('users', User::get()->pluck('full_name', 'id'));
    }
}

resources/views/project/create.blade.php
@extends('layouts.outer_form_partial')
@section('title','Projekt hinzufügen')
@section('head')

@endsection

@section('content')

@section('panel_heading','Projekt hinzufügen')
@section('panel_body')

    {!!  Form::open(['method'=>'post','url' => 'project/','class' => 'form-horizontal','role'=>'form']) !!}
    @include('project.form_partial')


    @include('layouts.form_buttons_partial')


    {!! Form::close() !!}
@endsection

resources/views/project/edit.blade.php
@extends('layouts.outer_form_partial')
@section('title','Projekt bearbeiten')


@section('panel_heading','Projekt bearbeiten')

@section('panel_body')

    @if(isset($_REQUEST['type']))
        {!!  Form::model($project,['method'=>'patch','url' => 'project/'.$project->id.'?type='.$_REQUEST['type'],'class' =>'form-horizontal','role'=>'form']) !!}
    @else
        {!!  Form::model($project,['method'=>'patch','url' => 'project/'.$project->id,'class' =>'form-horizontal','role'=>'form']) !!}
    @endif

    @include('project.form_partial')

    @include('layouts.form_buttons_partial')


    {!! Form::close() !!}

@endsection

resources/views/project/form_partial.blade.php
<div class="form-group">
    {!!Form::label('name','Name',['class' => 'control-label col-sm-2 pull-left'])!!}
    <div class="col-sm-8 col-sm-offset-1">
        {!!Form::text('name',NULL,['class' => 'form-control','required' => 'required'])!!}
        @include('layouts.display_error',['field_name'=>'name'])
    </div>
</div>

<div class="form-group">
    {!!Form::label('user_id','Betreuer',['class' => 'control-label col-sm-2 pull-left'])!!}
    <div class="col-sm-8 col-sm-offset-1">
        @if(Auth::check())
            {!!Form::select('user_id',$users,NULL,['class' => 'selectpicker form-control','data-live-search'=>'true','required' => 'required','size'=>'8'])!!}
        @else
            {!!Form::select('user_id',$users,NULL,['class' => 'selectpicker form-control','data-live-search'=>'true','required' => 'required','size'=>'8'])!!}
        @endif
    </div>
</div>


<div class="form-group">
    {!!Form::label('description','Status',['class' => 'control-label col-sm-2 pull-left'])!!}
    <div class="col-sm-8 col-sm-offset-1">
        {!!Form::textarea('description',NULL,['class' => 'form-control','rows'=>'3'])!!}
    </div>
</div>


@if(!isset($project) || $project->isAirplane)
    <div class="form-group">
        {!!Form::label('flightReady','Flugklar',['class' => 'control-label col-sm-2'])!!}
        <div class="col-sm-8 col-sm-offset-1 ">
            {!!Form::checkbox('flightReady')!!}
        </div>
    </div>


<div class="form-group">
    {!!Form::label('isAirplane','Flugzeug',['class' => 'control-label col-sm-2'])!!}
    <div class="col-sm-8 col-sm-offset-1 ">
        {!!Form::checkbox('isAirplane')!!}
    </div>
</div>
@endif

@if(Auth::user()->is_admin || !isset($project))
    <div class="form-group">
        {!!Form::label('active','Aktiv',['class' => 'control-label col-sm-2'])!!}
        <div class="col-sm-8 col-sm-offset-1 ">
            {!!Form::checkbox('active')!!}
        </div>
    </div>
@endif

resources/views/project/index.blade.php
@extends('layouts.layout')


@section('title','Übersicht')

@section('content')

    <div style="margin-bottom: 3%">
        @include('project.show_all_toggle_')
    </div>
    <div class="row col-md-4 col-md-offset-4" >

        <?php setlocale(LC_TIME, 'German') ?>

        <h3>Meiste Baustunden im {{\Carbon\Carbon::today()->subMonthNoOverflow()->formatLocalized('%B')}}</h3>
            <table class='table'>
        @foreach($top3 as $top)

                    <tr>
        @if($top->nickname=="")
            <h4><td>{{$top->first_name}}</td> <td>{{Help::format_time($top->Zeit)}}</td></h4>
        @else
            <h4><td>{{$top->nickname}}</td> <td>{{Help::format_time($top->Zeit)}}</td></h4>
        @endif
                    </tr>
        @endforeach
        </table>
    </div>
    <div class="row">
        @foreach($projects as $project)
            <div class="col-md-6">
                @include('project.overview_')
            </div>
        @endforeach

    </div>

@endsection

resources/views/project/overview_.blade.php
<!-- $project variable  must  be defined!! -->
<a href="{{url('/project/'.$project->id)}}" style="color: black;text-decoration: none">
    <div class="panel panel-default" style="height: 230px; overflow:auto ">
        <div class="panel-heading">
            <h3 class="panel-title">{{$project->name}}</h3>
        </div>
        <div class="panel-body" style="min-height: 150px;">
            <dl class="dl-horizontal">

                <dt>Verantwortlicher</dt>
                <dd>{{$project->supervisor_string}}</dd>
                @if($project->isAirplane)
                    <dt>Flugklar</dt>
                    <dd>{{$project->flight_ready_string}}</dd>

                @endif
                <dt >Offene Aufgaben</dt>
                <dd style="max-height: 70px; overflow:auto ">
                    @if($project->open_issues()->count() == 0)
                        Keine
                    @else
                        @foreach($project->open_issues() as $palaverItem)
                            {{$palaverItem->title}},
                        @endforeach
                    @endif
                </dd>
                <dt>Arbeit diese Woche</dt>
                <dd>{{Help::format_time($project->work_this_week)}}</dd>
                <dt>Arbeit diesen Monat</dt>
                <dd>{{Help::format_time($project->work_this_month)}}</dd>
                <dt>Arbeit dieses Jahr</dt>
                <dd>{{Help::format_time($project->work_this_year)}}</dd>

            </dl>
        </div>
    </div>
</a>

resources/views/project/palaverItem_overview_.blade.php
<!-- $palaverItem variable  must  be defined!! -->

<a href="{{url('/palaverItem/'.$palaverItem->id)}}" style="color: black;text-decoration: none">
    <div class="panel panel-default" style="height: 215px; overflow:auto ">
        <div class="panel-heading"
             @if($palaverItem->canceled)
             id="gradRed"
             @elseif($palaverItem->done)
             id="gradGreen"
                @endif
        >
            <h3 class="panel-title">{{$palaverItem->title}}</h3>
        </div>
        <div class="panel-body" style="min-height: 150px;">
            <dl class="dl-horizontal">

                <dt>Verantwortlich</dt>
                <dd>{{$palaverItem->responsible_users}}</dd>

                @if($palaverItem->active)
                    <dt>Status</dt>
                    <dd style="max-height: 65px; overflow:auto ">
                        @if(strlen($palaverItem->status)>0)
                            {{$palaverItem->status}}
                        @else
                            ---
                        @endif
                    </dd>
                    @unless(empty($palaverItem->date))
                    <dt>Termin</dt>
                    <dd>{{\Carbon\Carbon::parse($palaverItem->date)->format('d.m.Y')}}</dd>
                    @endunless
                    <dt>Arbeit diese Woche</dt>
                    <dd>{{Help::format_time($palaverItem->work_this_week)}}</dd>
                    <dt>Arbeit diesen Monat</dt>
                    <dd>{{Help::format_time($palaverItem->work_this_month)}}</dd>
                    <dt>Arbeit dieses Jahr</dt>
                    <dd>{{Help::format_time($palaverItem->work_this_year)}}</dd>
                @else
                    <dt>Gesamtarbeitszeit</dt>
                    <dd>{{Help::format_time($palaverItem->total_work_time)}}</dd>
                    @if($palaverItem->canceled)
                        <h3 style="text-align: center">Aufgabe gescheitert</h3>
                    @elseif($palaverItem->done)
                        <h3 style="text-align: center">Aufgabe erfolgreich abgeschlossen</h3>
                    @endif
                @endif

            </dl>
        </div>
    </div>
</a>

resources/views/project/show_all_toggle_.blade.php
@if(isset($show_all)&&$show_all)
    <a href='/project?show_all=0'>
        <button class="btn btn-default" style="width: 200px">
            Alte Einträge ausblenden <span class="glyphicon glyphicon-minus" style="vertical-align:middle"></span>
        </button>
    </a>

@else
    <a href='/project?show_all=1'>
        <button class="btn btn-default" style="width: 200px">
            Alte Einträge anzeigen
            <span class="glyphicon glyphicon-time"></span>
        </button>
    </a>
@endif

resources/views/project/view.blade.php
@push('head')
<style>
    #gradGreen {

        background: -webkit-linear-gradient(right, rgba(255,0,0,0), green); /* For Safari 5.1 to 6.0 */
        background: -o-linear-gradient(left, rgba(255,0,0,0), green); /* For Opera 11.1 to 12.0 */
        background: -moz-linear-gradient(left, rgba(255,0,0,0), green); /* For Firefox 3.6 to 15 */
        background: linear-gradient(to left, rgba(255,0,0,0), green); /* Standard syntax (must be last) */
    }

    #gradRed {

        background: -webkit-linear-gradient(right, rgba(255,0,0,0), red); /* For Safari 5.1 to 6.0 */
        background: -o-linear-gradient(left, rgba(255,0,0,0), red); /* For Opera 11.1 to 12.0 */
        background: -moz-linear-gradient(left, rgba(255,0,0,0), red); /* For Firefox 3.6 to 15 */
        background: linear-gradient(to left, rgba(255,0,0,0), red); /* Standard syntax (must be last) */
    }

</style>
@endpush
@extends('layouts.layout')

@section('title','Übersicht')

@section('content')


    <h1 style="text-align: center"> {{$project->name}}</h1>
    <div class="col-md-12"> @include('project.show_all_toggle_')</div>
    <div class="col-md-12">
        <a href='/project/{{$project->id}}/edit'>
            <button class="btn btn-default" style="width: 200px">
                Bearbeiten <span class="glyphicon glyphicon-pencil" style="vertical-align:middle"></span>
            </button>
        </a>
    </div>
    <div class="col-md-12">

        @can('create',[\App\models\palaverItem::class,$project])
            <a href='/palaverItem/create?project={{$project->id}}'>
                <button class="btn btn-default" style="width: 200px;margin-bottom: 10px">
                    Aufgabe hinzufügen <span class="glyphicon glyphicon-plus" style="vertical-align:middle"></span>
                </button>
            </a>
        @endcan
    </div>

    <div class="row">
        <div class="panel panel-default col-md-8 col-md-offset-2">
            <div class="panel-body">
                <dl class="dl-horizontal ">
                    <h4>
                        <dt>Verantwortlich</dt>
                        <dd>{{$project->supervisor_string}}</dd>
                        @if($project->isAirplane)
                            <dt>Flugklar</dt>
                            <dd>{{$project->flight_ready_string}}</dd>
                        @endif
                        <dt>Arbeit Woche</dt>
                        <dd>{{Help::format_time($project->work_this_week)}}</dd>
                        <dt>Arbeit Monat</dt>
                        <dd>{{Help::format_time($project->work_this_month)}}</dd>
                        <dt>Arbeit Jahr</dt>
                        <dd>{{Help::format_time($project->work_this_year)}}</dd>
                    </h4>
                </dl>
            </div>
        </div>
    </div>


    <div class="row">
        @foreach($project->palaverItems as $palaverItem)
            <div class="col-md-6">
                @include('project.palaverItem_overview_')
            </div>
        @endforeach
    </div>

    <div class="row">
        <h3>Am Projekt beteiligt:</h3>
        {!! Statistic::getProjectHelpers($project->id)!!}
    </div>
@endsection